### ISSUE TITLE
`failed to retrieve some files` when trying to install build dependencies

### ISSUE THREAD

**Issue by zocker-160** [startergo/docker-makepkg#1]
I think it would be very useful to have `pacman -Syu --noconfirm` run inside `run.sh` as well, because otherwise installing dependencies will fail like this:
```
Total Download Size:    90.77 MiB
Total Installed Size:  454.83 MiB

:: Proceed with installation? [Y/n] 
:: Retrieving packages...
error: failed retrieving file 'python-3.10.1-2-x86_64.pkg.tar.zst' from mirror.pkgbuild.com : The requested URL returned error: 404
error: failed retrieving file 'python-3.10.1-2-x86_64.pkg.tar.zst' from mirror.rackspace.com : The requested URL returned error: 404
error: failed retrieving file 'python-3.10.1-2-x86_64.pkg.tar.zst' from mirror.leaseweb.net : The requested URL returned error: 404
warning: failed to retrieve some files
error: failed to commit transaction (unexpected error)
 llvm-libs-13.0.0-6-x86_64 downloading...
 mesa-21.3.4-1-x86_64 downloading...
 python-3.10.1-2-x86_64 downloading...
 gtk2-2.24.33-2-x86_64 downloading...
 wxgtk2-3.0.5.1-3-x86_64 downloading...
Errors occurred, no packages were upgraded.
```

EDIT: I pulled the latest version of the container, but sadly even daily builds might not be enough to always be up to date.

**Comment by startergo** [comment]
It is right here:
https://github.com/startergo/docker-makepkg/blob/main/Dockerfile#L5

**Comment by zocker-160** [comment]
??
> it would be very useful to have pacman -Syu --noconfirm **run inside run.sh as well**

**Comment by startergo** [comment]
I have no means of testing as it works for me. Is it working for you if you add it to :
https://github.com/startergo/docker-makepkg/blob/main/run.sh#L10

**Comment by zocker-160** [comment]
Yes adding `pacman -Syu --noconfirm` to `run.sh`  before running the `paru` command does fix my issue above, because it updates outdated packages to the latest version.

Since Arch is updating quite often, your weekly rebuild schedule for the container is often not enough, causing build errors because of outdated packages.

I think pulling updates on container start makes a lot of sense or maybe changing the build schedule to daily could also work.

**Comment by startergo** [comment]
Can you try this package? It should work without that addition.
https://github.com/whynothugo/docker-makepkg

**Comment by zocker-160** [comment]
no does not work either, it has exactly the same issue
```
:: Proceed with installation? [Y/n] 
:: Retrieving packages...
 llvm-libs-13.0.0-6-x86_64 downloading...
 mesa-21.3.4-1-x86_64 downloading...
 python-3.10.1-2-x86_64 downloading...
 gtk2-2.24.33-2-x86_64 downloading...
 wxgtk2-3.0.5.1-3-x86_64 downloading...
error: failed retrieving file 'python-3.10.1-2-x86_64.pkg.tar.zst' from mirror.pkgbuild.com : The requested URL returned error: 404
error: failed retrieving file 'python-3.10.1-2-x86_64.pkg.tar.zst' from mirror.rackspace.com : The requested URL returned error: 404
error: failed retrieving file 'python-3.10.1-2-x86_64.pkg.tar.zst' from mirror.leaseweb.net : The requested URL returned error: 404
warning: failed to retrieve some files
error: failed to commit transaction (unexpected error)
Errors occurred, no packages were upgraded.
```

**Comment by zocker-160** [comment]
I solved this issue in my own fork - thanks anyway
